package vars

import "github.com/csingo/ctool/config/typs"

var Tool = &typs.ToolConf{
	Version:               "v1.0.1",
	ProtoGenGoPackage:     "google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1",
	ProtoGenGoGrpcPackage: "google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0",
	ProtocDownload: &typs.ToolConf_ProtocAddr{
		Win:   "https://github.com/protocolbuffers/protobuf/releases/download/v3.19.1/protoc-3.19.1-win64.zip",
		Mac:   "https://github.com/protocolbuffers/protobuf/releases/download/v3.19.1/protoc-3.19.1-osx-x86_64.zip",
		Linux: "https://github.com/protocolbuffers/protobuf/releases/download/v3.19.1/protoc-3.19.1-linux-x86_64.zip",
	},
	WriteFiles: map[string][]string{
		"project::create": {
			"resource/template/.gitignore.tpl",
			"resource/template/README.md.tpl",
			"resource/template/Makefile.tpl",
			"resource/template/app/.gitkeep.tpl",
			"resource/template/autoload/.gitkeep.tpl",
			"resource/template/autoload/command.go.tpl",
			"resource/template/autoload/config.go.tpl",
			"resource/template/autoload/controller.go.tpl",
			"resource/template/autoload/loader.go.tpl",
			"resource/template/autoload/middleware.go.tpl",
			"resource/template/autoload/rpc.go.tpl",
			"resource/template/autoload/service.go.tpl",
			"resource/template/base/.gitkeep.tpl",
			"resource/template/base/cache/.gitkeep.tpl",
			"resource/template/bin/.gitkeep.tpl",
			"resource/template/bin/init.sh.tpl",
			"resource/template/config/.gitkeep.tpl",
			"resource/template/config/typs/.gitkeep.tpl",
			"resource/template/config/typs/CommandConf.go.tpl",
			"resource/template/config/typs/ConfigCenterConf.go.tpl",
			"resource/template/config/typs/DatabaseConf.go.tpl",
			"resource/template/config/typs/LogConf.go.tpl",
			"resource/template/config/typs/RedisConf.go.tpl",
			"resource/template/config/typs/RouteConf.go.tpl",
			"resource/template/config/typs/RpcConf.go.tpl",
			"resource/template/config/typs/ServerConf.go.tpl",
			"resource/template/config/vars/.gitkeep.tpl",
			"resource/template/config/vars/CommandConf.go.tpl",
			"resource/template/config/vars/ConfigCenterConf.go.tpl",
			"resource/template/config/vars/DatabaseConf.go.tpl",
			"resource/template/config/vars/LogConf.go.tpl",
			"resource/template/config/vars/RedisConf.go.tpl",
			"resource/template/config/vars/RouteConf.go.tpl",
			"resource/template/config/vars/RpcConf.go.tpl",
			"resource/template/config/vars/ServerConf.go.tpl",
			"resource/template/conn/.gitkeep.tpl",
			"resource/template/conn/database.go.tpl",
			"resource/template/conn/redis.go.tpl",
			"resource/template/core/.gitkeep.tpl",
			"resource/template/core/cCommand/.gitkeep.tpl",
			"resource/template/core/cCommand/Init.go.tpl",
			"resource/template/core/cCommand/State.go.tpl",
			"resource/template/core/cCommand/Types.go.tpl",
			"resource/template/core/cConfig/.gitkeep.tpl",
			"resource/template/core/cConfig/Center.go.tpl",
			"resource/template/core/cConfig/File.go.tpl",
			"resource/template/core/cConfig/Init.go.tpl",
			"resource/template/core/cConfig/Nacos.go.tpl",
			"resource/template/core/cConfig/Types.go.tpl",
			"resource/template/core/cHTTPClient/Request.go.tpl",
			"resource/template/core/cHelper/.gitkeep.tpl",
			"resource/template/core/cHelper/Array.go.tpl",
			"resource/template/core/cHelper/Env.go.tpl",
			"resource/template/core/cHelper/File.go.tpl",
			"resource/template/core/cHelper/Math.go.tpl",
			"resource/template/core/cHelper/String.go.tpl",
			"resource/template/core/cHelper/constants/randomType/Index.go.tpl",
			"resource/template/core/cLog/.gitkeep.tpl",
			"resource/template/core/cLog/Init.go.tpl",
			"resource/template/core/cMiddleware/.gitkeep.tpl",
			"resource/template/core/cMiddleware/Init.go.tpl",
			"resource/template/core/cMiddleware/Types.go.tpl",
			"resource/template/core/cRpc/.gitkeep.tpl",
			"resource/template/core/cRpc/Init.go.tpl",
			"resource/template/core/cRpc/Types.go.tpl",
			"resource/template/core/cServer/.gitkeep.tpl",
			"resource/template/core/cServer/Http.go.tpl",
			"resource/template/core/cServer/Init.go.tpl",
			"resource/template/core/cServer/State.go.tpl",
			"resource/template/core/cServer/Types.go.tpl",
			"resource/template/docker/.gitkeep.tpl",
			"resource/template/docker/Dockerfile.tpl",
			"resource/template/docker/deployment.yml.tpl",
			"resource/template/global/.gitkeep.tpl",
			"resource/template/global/typs.go.tpl",
			"resource/template/global/vars.go.tpl",
			"resource/template/response/.gitkeep.tpl",
			"resource/template/response/Function.go.tpl",
			"resource/template/response/Type.go.tpl",
			"resource/template/server/.gitkeep.tpl",
			"resource/template/server/main.go.tpl",
		},
		"app::create": {
			"resource/template/app/app/.gitkeep.tpl",
			"resource/template/app/app/command/.gitkeep.tpl",
			"resource/template/app/app/controller/.gitkeep.tpl",
			"resource/template/app/app/middleware/.gitkeep.tpl",
			"resource/template/app/app/service/.gitkeep.tpl",
			"resource/template/app/app/validator/.gitkeep.tpl",
			"resource/template/app/app/domain/.gitkeep.tpl",
			"resource/template/app/app/orm/.gitkeep.tpl",
		},
	},
}
